# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  version: ${{ github.sha }}
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  DATE_TIME: $(date +'%d-%m-%Y-%H-%M-%S')

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run:
        docker build . --file Dockerfile --tag phongvanngo/medusajs-backend:latest;
        docker tag phongvanngo/medusajs-backend:latest phongvanngo/medusajs-backend:${{ env.DATE_TIME }};
    
    - name: Push Docker Image
      run:
        docker login --username=${dockerhub_username} --password=${dockerhub_password};
        docker push phongvanngo/medusajs-backend:${{ env.DATE_TIME }};
        docker push phongvanngo/medusajs-backend:latest;

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh to DrDongPhuong commands using password 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: 
          cd matkinh53-uat/matkinh53-deployment/uat/backend/v1;
          docker pull phongvanngo/medusajs-backend:latest;
          docker-compose up -d;